#!/bin/bash

function add_host_redirection {
  exists=$(getent hosts $1)
  if [ -z "$exists" ]; then
    echo "127.0.0.1 $1" | sudo tee -a /etc/hosts > /dev/null
  fi
}

function wp_config_setup {
  path=$1
  username=$2
  password=$3
  [ ! -f  $path/wp-config.php ] && cp $path/wp-config-sample.php $path/wp-config.php
  sed -i "s/username_here/$username/g;s/database_name_here/$username/g;s/password_here/$password/g;s/localhost/mariadb/g;"  $path/wp-config.php
}

function root_domain {
  echo $1 | grep -oP '(.*?(?=\.\w{2,10}(\.\w{2,10})?$))'
}

case "$1" in
  w*)
    # Download Wordpress
    if [ ! -f ~/www/wordpress.tar.gz ]; then
      curl https://en-gb.wordpress.org/latest-en_GB.tar.gz -o ~/www/wordpress.tar.gz
    fi
    # Extract Wordpress
    if [ ! -d  ~/www/$2 ]; then
      pushd ~/www > /dev/null
      tar xfz wordpress.tar.gz
      [ ! -z $2 ] && mv ~/www/wordpress ~/www/$2
      popd > /dev/null
    fi
    # Add Hosts Redirection
    add_host_redirection $2
    # Setup Wordpress Config
    root=$(root_domain $2)
    wp_config_setup ~/www/$2 "${root}_wp" secret
    # Setup Database
    pushd ~/www/dev > /dev/null
    docker compose exec mariadb mysql -uroot -psecret -e "CREATE USER IF NOT EXISTS ${db}@'%' IDENTIFIED BY 'secret';"
    docker compose exec mariadb mysql -uroot -psecret -e "CREATE DATABASE IF NOT EXISTS ${db};"
    docker compose exec mariadb mysql -uroot -psecret -e "GRANT ALL PRIVILEGES ON ${db}.* TO ${db}@'%'"
    popd > /dev/null

    ;;
  *) cat << EOF
ssl-cert: Generates

Allowed options:
    wordpress {domain}
EOF
esac
